name: Test
on: [push]
jobs:
  # CypressによるE2Eテスト
  e2e:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start App
        run: |
          npm ci 
          npm run build
          npm start &

      - uses: cypress-io/github-action@v2
        with:
          wait-on: "http://localhost:3000"

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Cypress E2E Videos
          path: cypress/videos